# Global constants
SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT, = 1080, 720
FPS = 60

# Colours used
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
LIGHT_GREY = (170, 170, 170)  # Light shade of the button
DARK_GREY = (100, 100, 100)  # Light shade of the button
MENU_COLOUR = (60, 25, 60)  # Menu screen background colour

# Player
PLAYER_MAX_MASS = 50

# Mass bar
MASS_BAR_WIDTH = 250
MASS_BAR_HEIGHT = 20
MASS_BAR_X = SCREEN_WIDTH - 300
MASS_BAR_Y = 50

# Trash spawning
MIN_TRASH_SPEED = 5
MAX_TRASH_SPEED = 10
MIN_TRASH_MASS = 1
MAX_TRASH_MASS = 5
MIN_TRASH_SPEED_UNTIL_STATIONARY = 0.1
MAX_TRASH_PER_SPAWNER = 100
TRASH_SPAWN_PERIOD = 50
TRASH_SLOWDOWN_RATE = 0.99
TRASH_DISTANCE_TO_SUCK = 100
TRASH_DISTANCE_TO_DELETE = 30
TRASH_COLLECT_SPEED = 150

# Incinerator
INCINERATOR_SPEED = 5
INCINERATOR_RADIUS = 50

# Game over
TRASH_UNTIL_GAME_OVER = 50

# Menu settings
FONT_SIZE = 45

# File paths
PLAYER_SPRITESHEET_PATH = "resources/arrow.png"
TRASH_SPRITESHEET_PATH = "resources/trash_spritesheet.png"
INCINERATOR_SPRITESHEET_PATH = "resources/Incinerator.png"
BACKGROUND_IMAGE_PATH = "resources/Junkpit.png"

